github_token: 1730c630f8f59ffaedc36a91bb004c71c4a03a73

# Guest OS timezone
timezone: Asia/Kolkata

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: giapp-16

# Virtual machine IP
ip: 192.168.1.8

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 2048

environment: local